version: "3"

services:
  squid:
    image: docker.io/gsmlg/proxy:squid
    restart: unless-stopped
    environment:
      - PROXY_MODE
      - SQUID_WAIT=10
    volumes:
      - squid_logs:/var/log/squid
      - squid_cache:/var/cache/squid
  stunnel:
    image: docker.io/gsmlg/proxy:stunnel
    restart: unless-stopped
    environment:
      - PROXY_MODE
      - PROXY_SERVER
    ports:
      - "13128:443"
      - "3128:80"

volumes:
  squid_logs: {}
  squid_cache: {}

