version: "2"

services:
  acme:
    image: "gsmlg/acme:latest"
    restart: unless-stopped
    environment:
      - CF_Email=gsmlg.com@gmail.com
      - CF_Key
    volumes:
      - certs:/certs
  mirrors:
    image: "gsmlg/mirrors.gsmlg.org:latest"
    restart: unless-stopped
    environment:
      - NAME=mirrors
      - HOSTNAME=mirrors.gsmlg.org
    volumes:
      - mirrors_data:/mirrors
      - sites:/sites
  echo:
    image: "gsmlg/echo:latest"
    restart: unless-stopped
    environment:
      - NAME=echo
      - HOSTNAME=echo.gsmlg.org
    volumes:
      - sites:/sites
  squid:
    image: "gsmlg/proxy:squid"
    restart: unless-stopped
  stunnel:
    image: "gsmlg/proxy:stunnel"
    restart: unless-stopped
    ports:
      - "13128:443"
  gsmlg_org:
    image: "gsmlg/gsmlg.org:latest"
    restart: unless-stopped
    environment:
      - NAME=gsmlg_org
      - HOSTNAME=www.gsmlg.org
    ports:
      - "4369:4369"
  nginx:
    image: "gsmlg/proxy:nginx"
    restart: unless-stopped
    volumes:
      - nginx_logs:/var/log/nginx
      - sites:/etc/nginx/sites
      - certs:/etc/certs:ro
      - ./static.conf:/etc/nginx/conf.d/static.conf
      - /var/www/static:/var/www/static
    ports:
      - "443:443"
      - "80:80"

volumes:
  certs: {}
  sites: {}
  mirrors_data: {}
  nginx_logs: {}


