version: "2"

services:
  acme:
    image: "gsmlg/acme:latest"
    environment:
      - CF_Email=gsmlg.com@gmail.com
      - CF_Key
    volumes:
      - certs:/certs
  mirrors:
    image: "gsmlg/mirrors.gsmlg.org:latest"
    ports:
      - "10808:80"
    volumes:
      - mirrors_data:/mirrors
      - sites:/sites
  squid:
    image: "gsmlg/proxy:squid"
  stunnel:
    image: "gsmlg/proxy:stunnel"
    ports:
      - "13128:443"
  nginx:
    image: "gsmlg/proxy:nginx"
    volumes:
      - sites:/etc/nginx/sites
      - certs:/etc/certs
    ports:
      - 443
      - 80

volumes:
  certs: {}
  sites: {}
  mirrors_data: {}
